### ISSUE TITLE
[FEAT] streamlit 페이지 이동 버튼 구현

### ISSUE THREAD

**Issue by ganghe74** [boostcampaitech4lv23cv2/final-project-level2-cv-11#29]
# Overview
 - streamlit 에서 페이지 이동 버튼을 만들어야 한다. (결과 페이지로 이동하기 위해서)

https://extras.streamlit.app/Switch%20page%20function
`streamlit-extras` 패키지의 `switch_page` 함수를 이용하면 구현할 수 있다.

# Todo
- [x] `poetry` 에 `streamlit-extras` 패키지 추가
- [x] 결과 페이지 구현
- [x] 결과 페이지로 이동하는 버튼 구현
