### ISSUE TITLE
[REFACTOR] Poetry `pyproject.toml` 정리하기

### ISSUE THREAD

**Issue by ganghe74** [boostcampaitech4lv23cv2/final-project-level2-cv-11#38]
# Overview
 - 멘토님도 수정하면 좋겠다고 하신 부분인데, `pyproject.toml` 파일에 사용하지 않는 패키지가 일부 포함되어 있어서 정리하면 좋을 듯.
 - 프론트엔드, 백엔드 등에서 사용하는 패키지를 분리하는 것도 좋다고 하셨다.
 - 어렵게 모두 환경설정을 맞췄으니, **나중에 프로젝트 마무리하는 단계에 수행하면 좋을 것 같다.**

# Todo
- [x] 모델 훈련 테스트 과정 정리 
(세팅환경에서 잘 훈련되는지 확인해야되서)

그룹별 사용 패키지 분리
- [x] Product
- [ ] 폰트 classification 모델
- [x] 폰트 generation 모델

**Comment by Yera10** [comment]
font classification 모델에서 torchmetric이 torch 버전과 맞지 않음
